title: Hallessandro
description: Textos sobre música, jogos, livros, mídias físicas e reflexões.
theme: minima

# Configurações do tema Minima
header_pages:
  - about.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag